// Generated by tools/build_subscriptions.js — do not edit manually.
globalThis.STATIC_TRACKER_BLOCKS = 12000;
globalThis.STATIC_GENERIC_BLOCKS = 13974;
globalThis.STATIC_SUBSCRIPTION_RULES = 29000;
globalThis.STATIC_BUILTIN_RULES = 32;
