// Generated by tools/build_subscriptions.js — do not edit manually.
globalThis.STATIC_RULES_TOTAL = 115412;
globalThis.STATIC_AG_RULES = 1650;
globalThis.STATIC_EP_RULES = 54524;
globalThis.STATIC_EL_RULES = 59170;
globalThis.STATIC_ADS_RULES = 68;
