// Generated by tools/build_subscriptions.js — do not edit manually.
globalThis.STATIC_POPUP_BLOCKS = 1000;
globalThis.STATIC_TRACKER_BLOCKS = 12000;
globalThis.STATIC_GENERIC_BLOCKS = 13470;
globalThis.STATIC_SUBSCRIPTION_RULES = 29500;
globalThis.STATIC_BUILTIN_RULES = 42;
