// Собирает упакованный срез фильтров для мгновенной защиты после установки.
// Запуск: node tools/build_subscriptions.js
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const root = path.resolve(__dirname, "..");
const sandbox = { console, setTimeout, clearTimeout, URL, AbortController, globalThis: {} };
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(path.join(root, "lib", "filters.js"), "utf8"), sandbox);

const sourceFiles = {
  easylist: path.join(__dirname, "easylist.txt"),
  "adguard-ru": path.join(__dirname, "adguard_ru.txt"),
  easyprivacy: path.join(__dirname, "easyprivacy.txt"),
};

const parsed = Object.entries(sourceFiles).map(([name, file]) => ({
  name,
  ...sandbox.parseFilters(fs.readFileSync(file, "utf8")),
}));
const result = sandbox.buildSubscriptionRules(parsed);
const builtinRules = JSON.parse(fs.readFileSync(path.join(root, "rules", "ads_rules.json"), "utf8"));

fs.writeFileSync(
  path.join(root, "rules", "subscriptions.json"),
  `${JSON.stringify(result.rules, null, 2)}\n`,
  "utf8"
);
fs.writeFileSync(
  path.join(root, "lib", "static-meta.js"),
  `// Generated by tools/build_subscriptions.js — do not edit manually.\n` +
  `globalThis.STATIC_POPUP_BLOCKS = ${result.meta.staticPopupBlocks};\n` +
  `globalThis.STATIC_TRACKER_BLOCKS = ${result.meta.staticTrackerBlocks};\n` +
  `globalThis.STATIC_GENERIC_BLOCKS = ${result.meta.staticGenericBlocks};\n` +
  `globalThis.STATIC_SUBSCRIPTION_RULES = ${result.rules.length};\n` +
  `globalThis.STATIC_BUILTIN_RULES = ${builtinRules.length};\n`,
  "utf8"
);

console.log(`subscriptions.json: ${result.rules.length} rules`);
console.log(`built-in rules: ${builtinRules.length}`);
console.log(`popup blocks: ${result.meta.staticPopupBlocks}`);
console.log(`tracker offset: ${result.meta.staticTrackerBlocks}`);
console.log(`generic offset: ${result.meta.staticGenericBlocks}`);
