// AdGuardian — сборка статических срезов фильтров для Manifest V3 Declarative Net Request.
// Правила разбиваются на наборы до 30 000 правил в файле, что позволяет загружать
// 100% всех правил EasyList, EasyPrivacy и AdGuard RU без обрезки.
// Запуск: node tools/build_subscriptions.js
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const root = path.resolve(__dirname, "..");
const sandbox = { console, setTimeout, clearTimeout, URL, AbortController, globalThis: {} };
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(path.join(root, "lib", "filters.js"), "utf8"), sandbox);

function findSourcePath(baseNames) {
  for (const name of baseNames) {
    const p1 = path.join(__dirname, name);
    if (fs.existsSync(p1)) return p1;
    const p2 = path.join(__dirname, "cache", name);
    if (fs.existsSync(p2)) return p2;
  }
  throw new Error(`Файл не найден среди: ${baseNames.join(", ")}`);
}

const sourceFiles = {
  "adguard-ru": findSourcePath(["adguard_ru.txt", "ag.txt"]),
  easyprivacy: findSourcePath(["easyprivacy.txt"]),
  easylist: findSourcePath(["easylist.txt"]),
};

console.log("Загрузка и парсинг списков фильтров...");
const parsed = {};
for (const [name, filePath] of Object.entries(sourceFiles)) {
  const text = fs.readFileSync(filePath, "utf8");
  parsed[name] = sandbox.parseFilters(text);
  console.log(`- ${name}: ${parsed[name].blocks.length} блокировок, ${parsed[name].allows.length} исключений`);
}

function compileRules(parsedList, maxPerChunk = 29500) {
  const rules = [];
  const used = new Set();
  for (const rule of [...(parsedList.allows || []), ...(parsedList.blocks || [])]) {
    const key = sandbox.ruleKey(rule);
    if (used.has(key)) continue;
    used.add(key);
    rules.push(rule);
  }

  if (rules.length <= maxPerChunk) {
    return [rules.map((r, i) => ({ id: i + 1, ...r }))];
  }

  const chunksCount = Math.ceil(rules.length / maxPerChunk);
  const chunkSize = Math.ceil(rules.length / chunksCount);
  const chunks = [];
  for (let i = 0; i < chunksCount; i++) {
    const slice = rules.slice(i * chunkSize, (i + 1) * chunkSize);
    chunks.push(slice.map((r, idx) => ({ id: idx + 1, ...r })));
  }
  return chunks;
}

const agChunks = compileRules(parsed["adguard-ru"]);
const epChunks = compileRules(parsed["easyprivacy"]);
const elChunks = compileRules(parsed["easylist"]);

const rulesDir = path.join(root, "rules");
if (!fs.existsSync(rulesDir)) fs.mkdirSync(rulesDir, { recursive: true });

// Запись AdGuard RU
fs.writeFileSync(path.join(rulesDir, "adguard_ru.json"), JSON.stringify(agChunks[0], null, 2), "utf8");
console.log(`adguard_ru.json: ${agChunks[0].length} правил`);

// Запись EasyPrivacy (chunks)
epChunks.forEach((chunk, i) => {
  const filename = `easyprivacy_${i + 1}.json`;
  fs.writeFileSync(path.join(rulesDir, filename), JSON.stringify(chunk, null, 2), "utf8");
  console.log(`${filename}: ${chunk.length} правил`);
});

// Запись EasyList (chunks)
elChunks.forEach((chunk, i) => {
  const filename = `easylist_${i + 1}.json`;
  fs.writeFileSync(path.join(rulesDir, filename), JSON.stringify(chunk, null, 2), "utf8");
  console.log(`${filename}: ${chunk.length} правил`);
});

const adsRulesRaw = fs.readFileSync(path.join(rulesDir, "ads_rules.json"), "utf8");
const adsRules = JSON.parse(adsRulesRaw);

const totalStatic = adsRules.length + agChunks[0].length +
  epChunks.reduce((acc, c) => acc + c.length, 0) +
  elChunks.reduce((acc, c) => acc + c.length, 0);

fs.writeFileSync(
  path.join(root, "lib", "static-meta.js"),
  `// Generated by tools/build_subscriptions.js — do not edit manually.\n` +
  `globalThis.STATIC_RULES_TOTAL = ${totalStatic};\n` +
  `globalThis.STATIC_AG_RULES = ${agChunks[0].length};\n` +
  `globalThis.STATIC_EP_RULES = ${epChunks.reduce((acc, c) => acc + c.length, 0)};\n` +
  `globalThis.STATIC_EL_RULES = ${elChunks.reduce((acc, c) => acc + c.length, 0)};\n` +
  `globalThis.STATIC_ADS_RULES = ${adsRules.length};\n`,
  "utf8"
);

console.log(`\nУСПЕШНО: Всего активных статических правил: ${totalStatic}`);
